branch-defaults:
  develop:
    environment: null
global:
  application_name: meanjsapp
  default_ec2_keyname: test
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
